cat('\014')
setwd("~/work/custdata")
custdata <- read.table("custdata.tsv", sep='\t', header=T)
colnames(custdata)
summary(custdata$income)
#install.packages("ggplot2")
library("ggplot2")
ggplot(custdata) + geom_histogram(aes(x=age), binwidth=5, fill="gray")
library(scales)
ggplot(custdata) + geom_density(aes(x=income)) + scale_x_continuous(labels=dollar)
ggplot(custdata) + geom_density(aes(x=income)) + scale_x_log10(breaks=c(100,1000,10000,100000),labels=dollar) + annotation_logticks(sides="bt")
ggplot(custdata) + geom_bar(aes(x=marital.stat), fill="orange")

statesums <- table(custdata$state.of.res)
statef <-as.data.frame(statesums)
colnames(statef) <-c("State.of.Residence", "Count")
summary(statef)
statef <- transform(statef, State.of.Residence=reorder(State.of.Residence, Count))
ggplot(statef) + geom_bar(aes(x=State.of.Residence,y=Count), stat="identity", fill="orange") + coord_flip() + theme(axis.text.y=element_text(size=rel(0.8)))